### ISSUE TITLE
train error!!!!!

### ISSUE THREAD

**Issue by spy001s** [yuto3o/yolox#6]
hello
thanks for your coding
i get this error when i run the train.py files for yolov3 tiny models 
###########################################################################
Traceback (most recent call last):
  File "train.py", line 133, in <module>
    app.run(main)
  File "C:\ProgramData\Anaconda3\envs\tf1g2\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "C:\ProgramData\Anaconda3\envs\tf1g2\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "train.py", line 69, in main
    load_weights(model, init_weight)
  File "F:\1-project\object detection\yolox\yolox-master\core\utils\weight.py", line 25, in load_weights
    model.load_weights(weights_file_path, by_name=True, skip_mismatch=True)
TypeError: load_weights() got an unexpected keyword argument 'skip_mismatch'
#####################################################################################
thanks for helping

**Comment by yuto3o** [comment]
we use tensorflow2.1

**Comment by VYXUOF** [comment]
I have encountered this problem before, when I upgraded tensorflow and keras to 2.1, it can run
